#!/usr/bin/env bash
# instructions to setup dotfile on new machine

#sets BaseDir
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# gitconfig
ln -s ${BASEDIR}/gitconfig ~/.gitconfig

# vim
ln -s ${BASEDIR}/vimrc ~/.vimrc

# tmux
ln -s ${BASEDIR}/tmux ~/.tmux.conf

# bash_profile
ln -s ${BASEDIR}/profile ~/.bash_profile

# vim plugin folder in path /.vim/pack/vendor/start
ln -s ${BASEDIR}/vim/ ~/.vim
