#!/usr/bin/env bash
# instructions to setup dotfile on new machine

#sets BaseDir
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# gitconfig
ln -s ${BASEDIR}/.gitconfig ~/.gitconfig

# vim
ln -s ${BASEDIR}.vimrc ~/.vimrc

# tmux
ln -s ${BASEDIR}/.tmux.conf ~/.tmux.conf

# bash_profile
ln -s ${BASEDIR}/.bash_profile ~/.bash_profile

# vim plugin folder in path /.vim/pack/vendor/start
#ln -s ${BASEDIR}/vim/pack ~/.vim/pack
